FROM hasura/graphql-engine:v2.22.0

RUN curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

RUN cd /home/hasura && hasura init .

COPY ./etc/hasura/metadata/ ./home/hasura/metadata
COPY ./etc/hasura/migrations/ ./home/hasura/migrations
